version: '3'
services:
  php:
    build:
      context: ./php-fpm/.
    volumes:
      - ./app:/var/www/app
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
  web:
    image: nginx:latest
    ports:
      - "8888:80"
#      - "9051:9051"
    volumes:
      - ./app:/var/www/app
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php