version: '3'

networks:
  default:
    ipam:
      config:
        - subnet: 172.31.202.0/24

services:
  php:
    build:
      context: ./php-fpm/.
#    ports:
#      - "8888:9000"
    volumes:
      - ./app:/var/www/app
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
  web:
    image: nginx:latest
    ports:
      - "8888:80"

    volumes:
      - ./app:/var/www/app
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php